// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fX2pFD_m6mJXbF_htvsTgjGzccDBHKI',
    appId: '1:234545800256:android:4e79be10759dacf60d2ba5',
    messagingSenderId: '234545800256',
    projectId: 'testing-6058c',
    databaseURL: 'https://testing-6058c-default-rtdb.firebaseio.com',
    storageBucket: 'testing-6058c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRqjsK9SPyrhantA83xc7zmdksRlkBDE',
    appId: '1:443119990978:ios:e52cd4cd2421599064a35b',
    messagingSenderId: '443119990978',
    projectId: 'tgo-task',
    storageBucket: 'tgo-task.firebasestorage.app',
    iosClientId: '443119990978-s1ov53qajn0su35op92baehurkmt29rp.apps.googleusercontent.com',
    iosBundleId: 'com.tgo.tgoTodo',
  );
}